# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml
github: https://github.com/JohnWey
logo_title: MyLogo
blog_title: JohnWey's Blog

# Content
excerpt_link: Read More
fancybox: true
mathjax: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- tag
- archive

# Miscellaneous
wx_block: false
google_analytics:
favicon:
twitter:
google_plus:
fb_admins:
fb_app_id:

# Duoshuo
duoshuo_shortname:

# Swiftype Search
swiftype_key:
